apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}