version: '3.9'

services:
  #       DBs
  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"          # user-db pe portul default local
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  product-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productsdb
    ports:
      - "5434:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ordersdb
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  payment-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paymentsdb
    ports:
      - "5436:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  #       MICROSERVICES
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@user-db:5432/usersdb?schema=public
      JWT_SECRET: super-secret-jwt-key-2025
    depends_on:
      - user-db
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             node src/server.js"
    restart: unless-stopped

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@product-db:5432/productsdb?schema=public
      JWT_SECRET: super-secret-jwt-key-2025
    depends_on:
      - product-db
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             node src/server.js"
    restart: unless-stopped

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:password@order-db:5432/ordersdb?schema=public
      JWT_SECRET: super-secret-jwt-key-2025
      USER_SERVICE_URL: http://user-service:3000
      PRODUCT_SERVICE_URL: http://product-service:3001
    depends_on:
      - order-db
      - user-service
      - product-service
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             node src/server.js"
    restart: unless-stopped

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgresql://postgres:password@payment-db:5432/paymentsdb?schema=public
      JWT_SECRET: super-secret-jwt-key-2025
      USER_SERVICE_URL: http://user-service:3000
      ORDER_SERVICE_URL: http://order-service:3002
    depends_on:
      - payment-db
      - user-service
      - order-service
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             node src/server.js"
    restart: unless-stopped

volumes:
  user_db_data:
  product_db_data:
  order_db_data:
  payment_db_data: