apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1rZXktMjAyNQ==   # echo -n "super-secret-jwt-key-2025" | base64
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
